apiVersion: v1
kind: Service
metadata:
  name: graphite
  namespace: graphite
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: carbon-tcp
      port: 2003
      targetPort: 2003
    - name: carbon-tcp-alt
      port: 2004
      targetPort: 2004
    - name: carbon-udp
      port: 2023
      targetPort: 2023
    - name: carbon-udp-alt
      port: 2024
      targetPort: 2024
    - name: statsd
      port: 8125
      protocol: UDP
      targetPort: 8125
    - name: statsd-admin
      port: 8126
      targetPort: 8126
  selector:
    app: graphite