server:
   ha:
      enabled: true
      raft:
         enabled: true
         setNodeId: true
         config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }

            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = true
               ui = true
            }

            service_registration "kubernetes" {}
      activeService:
         enabled: true
         type: LoadBalancer
         annotations:
            metallb.universe.tf/address-pool: "default"
   dataStorage:
      enabled: true
      size: 10Gi
