- name: Disable enterprise repos
  command: sed -i '/^deb https:\/\/enterprise.proxmox.com/s/^deb/#deb/' /etc/apt/sources.list.d/pve-enterprise.list

- name: Disable enterprise ceph repos
  command: sed -i '/^deb https:\/\/enterprise.proxmox.com/s/^deb/#deb/' /etc/apt/sources.list.d/ceph.list

- name: Ensure the no-subscription line is in the ceph.list file
  lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    line: "deb http://download.proxmox.com/debian/ceph-reef {{ ansible_distribution_release }} no-subscription"

- name: Add no-subscription and Debian repos
  template:
    src: proxmox_repo.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Update all packages
  apt:
    upgrade: dist

- name: Ensure necessary packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    