apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphite-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: "{{ .Values.persistence.path }}"