- name: Configure Proxmox Cluster
  #hosts: pve03
  hosts: all
  gather_facts: yes
  vars:
    primary_node: "{{ hostvars[groups['all'][0]].ansible_host }}"
  vars_files:
    - ../vault/secrets.yml

  roles:
    - ../roles/packages
    - ../roles/establish_cluster
    - ../roles/create_ticket
    - ../roles/notifications
    - ../roles/certificates

