- name: Configure Proxmox Cluster
  #hosts: pve03
  hosts: all
  gather_facts: yes
  vars_files:
    - ../vault/secrets.yml
  roles:
    #- ../roles/packages
    #- ../roles/establish_cluster
    - ../roles/create_ticket
    - ../roles/notifications  # Due to the cluster fs being protected, this will fail

