- name: Set username as fact
  set_fact:
    proxmox_username: root@pam
    passwd_file: /tmp/.proxmox_password
  delegate_to: localhost
  run_once: yes

- name: Write cluster password to file
  copy:
    content: "{{ cluster_password }}"
    dest: "{{ passwd_file }}"
    owner: root
    group: root
    mode: '0600'
  delegate_to: localhost
  run_once: yes

- name: Generate Proxmox ticket
  uri:
    url: https://{{ primary_node }}:8006/api2/json/access/ticket
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ proxmox_username }}"
      password: "{{ lookup('file', passwd_file) }}"
    validate_certs: no
  register: ticket
  delegate_to: localhost
  run_once: yes

- name: Print time when ticket expires
  debug:
    var: ticket.date
  delegate_to: localhost
  run_once: yes

- name: Set ticket as fact
  set_fact:
    proxmox_ticket: "{{ ticket.json.data.ticket }}"
  delegate_to: localhost
  run_once: yes

- name: Set CSRF token as fact
  set_fact:
    proxmox_csrf: "{{ ticket.json.data.CSRFPreventionToken }}"
  delegate_to: localhost
  run_once: yes

#- name: Delete cluster password file
#  file:
#    path: "{{ passwd_file }}"
#    state: absent
#  delegate_to: localhost
#  run_once: yes

