---
- name: GET notification targets
  uri:
    url: https://{{ primary_node }}:8006/api2/json/cluster/notifications/endpoints/smtp
    method: GET
    headers:
      CSRFPreventionToken: "{{ proxmox_csrf }}"
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
    validate_certs: no
  register: notification_targets
  delegate_to: localhost
  run_once: yes

- name: Create GMail endpoint
  uri:
    url: https://{{ primary_node }}:8006/api2/json/cluster/notifications/endpoints/smtp
    method: POST
    headers:
      CSRFPreventionToken: "{{ proxmox_csrf }}"
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
      Content-Type: "application/json"
    validate_certs: no
    body: >
      {
        "from-address": "proxmox.{{ cluster_name }}@{{ ansible_domain }}",
        "name": "Gmail",
        "server": "smtp.gmail.com",
        "mailto": "{{ to_address }}",
        "mailto-user": "root@pam",
        "mode": "tls",
        "password": "{{ gmail_app_password }}",
        "port": 465,
        "username": "{{ gmail_username }}"
      }
    body_format: json
  delegate_to: localhost
  run_once: yes
  when: notification_targets.json.data | selectattr('name', 'equalto', 'Gmail') | list | length == 0

- name: GET notification matcher
  uri:
    url: https://{{ primary_node }}:8006/api2/json/cluster/notifications/matchers
    method: GET
    headers:
      CSRFPreventionToken: "{{ proxmox_csrf }}"
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
    validate_certs: no
  register: notification_matchers
  delegate_to: localhost
  run_once: yes

- name: Create notification matcher
  uri:
    url: https://{{ primary_node }}:8006/api2/json/cluster/notifications/matchers
    method: POST
    headers:
      CSRFPreventionToken: "{{ proxmox_csrf }}"
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
      Content-Type: "application/json"
    validate_certs: no
    body: >
      {
        "name": "Gmail-matcher",
        "comment": "Send all notifications to Gmail",
        "mode": "all",
        "target": [ "Gmail" ]
      }
    body_format: json
  delegate_to: localhost
  run_once: yes
  when: notification_matchers.json.data | selectattr('name', 'equalto', 'Gmail-matcher') | list | length == 0

- name: Send a test notification
  uri:
    url: https://{{ primary_node }}:8006/api2/json/cluster/notifications/targets/Gmail/test
    method: POST
    headers:
      CSRFPreventionToken: "{{ proxmox_csrf }}"
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
    validate_certs: no
  delegate_to: localhost
  run_once: yes
  