services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8112 # deluge web interface
      - 58846:58846 # deluge RPC
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 6767:6767 # bazarr
    volumes:
      - /home/werner/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${openvpn_user}
      - OPENVPN_PASSWORD=${openvpn_password}
      - SERVER_COUNTRIES=New Zealand
      - SERVER_CITIES=Auckland
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - NZBGET_USER=username
      - NZBGET_PASS=password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/werner/nzbget:/config
      - /media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/werner/sonarr:/config
      - /media:/media
    #ports:
    #  - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/werner/radarr:/config
      - /media:/media
    #ports:
    #  - 7878:7878

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/werner/bazarr:/config
      - /media:/media
    #ports:
    #  - 6767:6767

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/werner/prowlarr:/config
    restart: unless-stopped

#  lidarr:
#    container_name: lidarr
#    image: lscr.io/linuxserver/lidarr:latest
#    restart: unless-stopped
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/brandon/lidarr:/config
#      - /media/data:/data
#    environment:
#     - PUID=1000
#     - PGID=100
#     - TZ=America/Los_Angeles
#    ports:
#      - 8686:8686

#  readarr:
#    image: lscr.io/linuxserver/readarr:develop
#    container_name: readarr
#    environment:
#      - PUID=1000
#      - PGID=100
#      - TZ=America/Los_Angeles
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/brandon/readarr:/config
#      - /media/data:/data
#    ports:
#      - 8787:8787
#    restart: unless-stopped

#  deluge:
#    image: lscr.io/linuxserver/deluge:latest
#    container_name: deluge
#    restart: unless-stopped
#    environment:
#      - PUID=1000
#      - PGID=100
#      - TZ=Pacific/Auckland
#    volumes:
#      - /home/werner/deluge:/config
#      - /media/data:/data
#    network_mode: service:gluetun