# Keep the layout of the file as is, it is used by the ansible playbook to determine the hosts to run the tasks on.
# Use the hostname (not fqdn) as the key for the hosts, and the IP address as the value for ansible_host.
all:
  hosts:
    pve15:
      ansible_host: 192.168.20.15
    pve16:
      ansible_host: 192.168.20.16
  vars:
    ansible_user: root
    primary_node: 192.168.20.15
