# Considering the cluster being built will host all internal DNS, we have to use IP addresses instead of hostnames
all:
  hosts:
    pve01:
      ansible_host: 192.168.75.11
    pve02:
      ansible_host: 192.168.75.12
    pve03:
      ansible_host: 192.168.75.13
  vars:
    ansible_user: root
