# Keep the layout of the file as is, it is used by the ansible playbook to determine the hosts to run the tasks on.
# Use the hostname (not fqdn) as the key for the hosts, and the IP address as the value for ansible_host.
all:
  hosts:
    pve01:
      ansible_host: 192.168.22.11
    pve02:
      ansible_host: 192.168.22.12
    pve03:
      ansible_host: 192.168.22.13
    pve08:
      ansible_host: 192.168.22.18
  vars:
    ansible_user: root
