version: '3.8'

services:
  db:
    image: postgres:13
    container_name: netbox_db
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
      POSTGRES_DB: netbox
    volumes:
      - netbox_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netbox"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2
    container_name: netbox_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  netbox:
    image: netboxcommunity/netbox
    container_name: netbox
    environment:
      - NETBOX_ROOT_PASSWORD=${NETBOX_ROOT_PASSWORD:-netbox_root_pw}
      - DB_WAIT_DEBUG=1
      - SECRET_KEY=aVvS9vN0R3xmN0wzG5HmQ2yVQsD7g5hD5cZ9y4kQF4qZ9eKfZj
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=netbox
      - DB_WAIT_TIMEOUT=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NETBOX_URL=http://netbox:8080
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        /opt/netbox/netbox/manage.py migrate &&
        echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | /opt/netbox/netbox/manage.py shell &&
        /usr/local/bin/gunicorn -c /etc/netbox/config/gunicorn.py netbox.wsgi &&
        python3 /opt/netbox/populate_netbox.py
      "
    volumes:
      - ./populate_netbox.py:/opt/netbox/populate_netbox.py

volumes:
  netbox_db_data: