all:
  hosts:
    network-docker:
      ansible_host: 192.168.22.5
      ansible_user: werner
      ansible_become: true
      # MQTT credentials for Frigate integration
      mosquitto_frigate_user: "frigate"
      mosquitto_frigate_password: "8277e33e18420f8ff5ace06f884e1e09"
