apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphite-pvc
  namespace: graphite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}